import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const route = read("app/api/pricing/route/route.ts");
const form = read("components/booking/booking-form.tsx");
const middleware = read("middleware.ts");
const migration = read("supabase/migrations/008_secure_operations.sql");
const completionMigration = read("supabase/migrations/009_admin_completion.sql");
const driverApi = read("app/api/conductor/trips/route.ts");
const driverLogin = read("app/api/conductor/session/route.ts");
const driverSession = read("lib/auth/driver-session.ts");
const catalog = read("lib/data/catalog.ts");
const reservationEmail = read("lib/services/email.ts");

assert.match(route, /total: pricing\.amount/);
assert.doesNotMatch(route, /\.\.\.pricing|subtotal:|gatewayFee:|breakdown:/);
assert.doesNotMatch(form, /services\/pricing|COP_PER_KM|SURCHARGE/);
assert.match(middleware, /profile\.role !== "admin"/);
assert.match(middleware, /DRIVER_SESSION_COOKIE/);
assert.match(migration, /Drivers read assigned reservations/);
assert.match(migration, /audit_reservations/);
assert.match(migration, /Admins manage profiles/);
assert.match(driverApi, /getActiveDriverSession/);
assert.match(driverApi, /\.eq\("driver_id", session\.driverId\)/);
assert.match(driverApi, /Acceso de solo lectura/);
assert.doesNotMatch(driverApi, /\.update\(|isAllowedDriverTransition/);
assert.match(completionMigration, /drop policy if exists "Drivers update assigned reservations"/);
assert.match(completionMigration, /reservation_observations/);
assert.match(completionMigration, /Brayan Agudelo/);
assert.match(completionMigration, /bog-tour-prueba/);
assert.match(driverLogin, /verifyTurnstile/);
assert.match(driverLogin, /driver_login_attempts/);
assert.match(driverLogin, /GENERIC_ERROR/);
assert.match(driverSession, /expiresAt/);
assert.match(driverSession, /httpOnly|DRIVER_SESSION_COOKIE/);
assert.doesNotMatch(driverLogin, /role\s*:/);
assert.match(catalog, /id: "bog-tour-prueba"[\s\S]*basePrice: 1500/);
assert.match(reservationEmail, /reservation-customer-/);
assert.match(reservationEmail, /reservation-operations-/);
assert.match(reservationEmail, /Contactar por WhatsApp/);
assert.doesNotMatch(reservationEmail, /to: \[input\.customer\.email, process\.env\.OPERATIONS_EMAIL\]/);

console.log("Security contract checks passed.");
